package com.civichub.ai.task;

public enum AITaskType {
    REPORT_DESCRIPTION_ENHANCEMENT,
    REPORT_CATEGORY_CLASSIFICATION,
    DEPARTMENT_RECOMMENDATION,
    DUPLICATE_REPORT_ANALYSIS,
    IMAGE_OCR,
    RESOLUTION_EVIDENCE_ANALYSIS,
    REPORT_SUMMARY,
    SPATIAL_INSIGHT,
    IMAGE_CONTEXT
}
