package com.civichub.audit.enums;

public enum AuditAction {
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_ACTIVATED,
    CATEGORY_DEACTIVATED,
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_ACTIVATED,
    DEPARTMENT_DEACTIVATED,
    REPORT_ASSIGNED,
    REPORT_REASSIGNED,
    REPORT_STATUS_CHANGED,
    REPORT_CANCELLED
}
